# Generated by Django 5.0.1 on 2024-01-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order_history',
            field=models.TextField(default='[]'),
        ),
    ]
