# Generated by Django 5.0.1 on 2024-01-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_customer_order_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('coupon_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
