# Generated by Django 5.0.1 on 2024-01-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0005_coupons"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="offer/")),
                ("visibility", models.BooleanField(default=True, null=True)),
                ("available", models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="menuitem",
            name="available",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="discount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
