# Generated by Django 5.0.1 on 2024-01-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0006_flashoffer_menuitem_available_menuitem_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="categoryimg/"),
        ),
    ]
