# Generated by Django 5.0.1 on 2024-01-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0008_remove_menuitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
