# Generated by Django 5.0.1 on 2024-01-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0010_scrollingtext"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("mininum_order", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
