# Generated by Django 5.0.1 on 2024-02-01 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0013_loading_alter_category_id_alter_coupons_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteOrder",
            fields=[
                ("invoice", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField()),
                (
                    "order_status",
                    models.IntegerField(
                        choices=[(1, "In"), (2, "Baking"), (3, "Dispatched")]
                    ),
                ),
                ("menu_items", models.ManyToManyField(to="homepage.menuitem")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
