# Generated by Django 5.0.1 on 2024-02-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0014_websiteorder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="websiteorder",
            name="menu_items",
        ),
    ]
