# Generated by Django 5.0.1 on 2024-02-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0016_websiteitems"),
    ]

    operations = [
        migrations.AddField(
            model_name="websiteorder",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
