# Generated by Django 5.0.1 on 2024-02-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0019_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, editable=False, verbose_name="order"
            ),
        ),
    ]
