# Generated by Django 5.0.1 on 2024-02-03 07:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0020_alter_category_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(
                blank=True, default=django.utils.timezone.now, upload_to="images/"
            ),
            preserve_default=False,
        ),
    ]
