# Generated by Django 5.0.1 on 2024-02-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0021_alter_menuitem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
