# Generated by Django 5.0.1 on 2024-02-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0023_usercoupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupons",
            name="for_one_time",
            field=models.BooleanField(default=True),
        ),
    ]
