# Generated by Django 5.0.1 on 2024-02-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0024_coupons_for_one_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupons",
            name="for_one_time",
            field=models.BooleanField(default=False),
        ),
    ]
