# Generated by Django 5.0.1 on 2024-02-05 04:50

import django.core.validators
import homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0025_alter_coupons_for_one_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(
                upload_to="images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png"]
                    ),
                    homepage.models.validate_image_extension,
                ],
            ),
        ),
    ]
